

# This file was *autogenerated* from the file cloud.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2002 = Integer(2002); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_1024 = Integer(1024)
import socket
import json
HOST="127.0.0.1"
PORT=_sage_const_2002 

def prime_factorisation(num) :
    prime_factors=[]
    a=list(factor(num))
    for i in range(len(a)) :
        for j in range(int(a[i][_sage_const_1 ])) :
            prime_factors.append(int(a[i][_sage_const_0 ]))
    return prime_factors

with socket.socket(socket.AF_INET , socket.SOCK_STREAM) as s :
    s.bind((HOST,PORT))
    s.listen()
    print("_____Cloud Server On_____")
    print(f"Listening on {HOST} : {PORT} \n")
    try :
        while True :
            conn , addr =s.accept()
            print(f"Connection established with {addr}")
            raw_data=conn.recv(_sage_const_1024 ).decode()
            data=json.loads(raw_data)
            num=data["data"]
            primes = prime_factorisation(num)
            new_data={"data" : primes}
            conn.send(json.dumps(new_data).encode())
            print("____Connection ended____\n")
    except :
        print("Could not establish connection !!")



        

