

# This file was *autogenerated* from the file amicable.sage
from sage.all_cmdline import *   # import sage library

_sage_const_10 = Integer(10); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
index=_sage_const_10  #just change the value of index to get more amicable numbers
i=_sage_const_2 
num=_sage_const_0 
while True :
    sum_i=sigma(i,_sage_const_1 )-i
    sum_div=sigma(sum_i,_sage_const_1 )-sum_i
    if i==sum_div and sum_i!=i and sum_i>i :
        print(f"{num+_sage_const_1 }. {i} and {sum_i}")
        num+=_sage_const_1 
    if num==index :
        break
    i+=_sage_const_1 
    

